version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/services/orders-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/services/payments-worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/services/inventory-worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/services/streams-order-status"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/notifications-worker"
    schedule:
      interval: "weekly"
