clusters=primary,secondary
primary.bootstrap.servers=kafka1:9092,kafka2:9092,kafka3:9092
secondary.bootstrap.servers=dr-kafka1:9092

primary->secondary.enabled=true
primary->secondary.topics=orders.v1.events|payments.v1.events|inventory.v1.events|orders.v1.status|risk.v1.fraud_alerts|web.v1.clickstream|analytics.v1.product_metrics|analytics.v1.web_path_metrics|retry.v1.notifications.5s|retry.v1.notifications.1m|dlq.v1.notifications
primary->secondary.groups=.*
primary->secondary.sync.group.offsets.enabled=true
primary->secondary.emit.checkpoints.enabled=true
primary->secondary.sync.topic.configs.enabled=true
primary->secondary.sync.topic.acls.enabled=true
primary->secondary.replication.factor=1
primary->secondary.checkpoints.topic.replication.factor=1
primary->secondary.offset-syncs.topic.replication.factor=1
primary->secondary.heartbeats.topic.replication.factor=1
primary->secondary.emit.heartbeats.enabled=true
primary->secondary.refresh.topics.interval.seconds=15
primary->secondary.refresh.groups.interval.seconds=15

replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy
tasks.max=4
