version: "3.9"

services:
  kafka1:
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,PLAINTEXT:SSL,EXTERNAL:SSL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_KEY_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
    volumes:
      - ./security/certs/kafka1:/etc/kafka/secrets

  kafka2:
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,PLAINTEXT:SSL,EXTERNAL:SSL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_KEY_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
    volumes:
      - ./security/certs/kafka2:/etc/kafka/secrets

  kafka3:
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,PLAINTEXT:SSL,EXTERNAL:SSL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_KEY_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${KAFKA_SSL_CREDENTIALS_FILE:-certs_creds}
    volumes:
      - ./security/certs/kafka3:/etc/kafka/secrets
