apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: pulsemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: ghcr.io/example/pulsemart-orders-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: SCHEMA_REGISTRY_URL
            - name: ORDERS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: ORDERS_DB_URL
            - name: ORDERS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: ORDERS_DB_USER
            - name: ORDERS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: pulsemart
spec:
  selector:
    app: orders-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
